map_name = "plains_2.tmx"
character_sheet = "characters"
player_speed = 700
max_player_speed= 400
jump_force= 6000
initial_jump_time= 0.20
gravity= 1200
path_to_player_data = "./player"
post_level_secs = 10
squish_bounce_force = 200
trick_time = 500
dash_force = 5000
curve_pow= 1.2
grounded_decay = 0.2
wall_threshold = 5
grounded_threshold = 1